version: "3.2"

services:
  sonarqube-analyze:
    build:
      context: ./
      dockerfile: ./containers/sonarqube-analyze/Dockerfile
    environment:
      - SonarHostUrl="http://sonarqube:9000"
    depends_on:
      - sonarqube

  sonarqube:
    build:
      context: ./
      dockerfile: ./containers/sonarqube/Dockerfile
    ports:
      - 9000:9000
