version: "3.2"

services:
  sonarqube-analyze:
    build:
      context: ./
      dockerfile: ./containers/sonarqube-analyze/Dockerfile
    depends_on:
      - sonarqube

  sonarqube:
    image: sonarqube:6.7.5
    ports:
      - 9000:9000
