FROM sonarqube:6.7.5

# install newer SonarC# version
RUN wget -O $SONARQUBE_HOME/extensions/plugins/sonar-csharp-plugin-7.5.0.6605.jar "https://sonarsource.bintray.com/Distribution/sonar-csharp-plugin/sonar-csharp-plugin-7.5.0.6605.jar"
